Implement QoS 1
JavaSaBr/mqtt-broker pull request #21
Opened 2019-11-21 06:49 UTC by JavaSaBr

Implement QoS 1

2019-11-21 23:09 UTC, crazyrokr requested changes

2019-11-21 23:09 UTC, crazyrokr commented on src/main/java/com/ss/mqtt/broker/model/MqttPropertyConstants.java
> +    int PACKET_ID_MAX = 0xFFFF;
Is MAXIMUM_PACKET_ID the same ?

2019-11-21 23:09 UTC, crazyrokr commented on src/main/java/com/ss/mqtt/broker/model/impl/DefaultMqttSession.java
> +        pendingPublishes.runInWriteLock(publishes -> {
please extract to method

2019-11-21 23:09 UTC, crazyrokr commented on src/main/java/com/ss/mqtt/broker/model/impl/DefaultMqttSession.java
> +        var stamp = pendingPublishes.readLock();
runInReadLock can be used

2019-11-21 23:09 UTC, crazyrokr commented on src/main/java/com/ss/mqtt/broker/service/impl/InMemoryMqttSessionService.java
>      public @NotNull Mono<Boolean> store(@NotNull String clientId, @NotNull MqttSession session, long expiryInterval) {
Please make multi line

2019-11-22 05:49 UTC, JavaSaBr commented on src/main/java/com/ss/mqtt/broker/model/impl/DefaultMqttSession.java
> +        var stamp = pendingPublishes.readLock();
we don't have a version of this method with one object and one primitive argument

2019-11-23 07:22 UTC, crazyrokr requested changes

2019-11-23 07:22 UTC, crazyrokr commented on src/main/java/com/ss/mqtt/broker/model/impl/DefaultMqttSession.java
> +    private void removeExpiredPackets(@NotNull Array<PendingPublish> publishes) {
It can be static

2019-11-23 07:27 UTC, crazyrokr approved these changes

2019-11-23 07:28 UTC, merged