[broker-22] implement QoS 2
JavaSaBr/mqtt-broker pull request #28
Opened 2019-11-25 17:50 UTC by JavaSaBr

Implement QoS 2

2019-11-26 21:18 UTC, Wagos commented on src/main/java/com/ss/mqtt/broker/handler/packet/in/PublishAckInPacketHandler.java
> +        var session = client.getSession();
Is it possible to avoid code duplication in handlers? (PublishCompleteInPacketHandler.java, PublishReceiveInPacketHandler.java, PublishReleaseInPacketHandler.java )

2019-11-26 21:18 UTC, Wagos commented on src/main/java/com/ss/mqtt/broker/handler/publish/out/AbstractPublishOutHandler.java
> +        var packetOutFactory = client.getPacketOutFactory();
To much "client" for two lines. consider setting client in send() or getPacketOutFactory()

2019-11-28 20:13 UTC, crazyrokr requested changes

2019-11-28 20:13 UTC, crazyrokr commented on src/main/java/com/ss/mqtt/broker/model/impl/DefaultMqttSession.java
> +    public void registerOutPublish(@NotNull PublishInPacket publish,
Wrong formatting

2019-11-28 20:13 UTC, crazyrokr commented on src/test/groovy/com/ss/mqtt/broker/test/integration/ConnectSubscribePublishTest.groovy
> +            def subscribeResult = subscriber.subscribeWith()
Please extract subscribe and publish to function

2019-11-29 18:15 UTC, crazyrokr requested changes

2019-11-29 18:15 UTC, crazyrokr commented on src/main/java/com/ss/mqtt/broker/model/impl/DefaultMqttSession.java
> +        @NotNull PendingPacketHandler handler, int packetId
Wrong formatting

2019-11-29 18:15 UTC, crazyrokr commented on src/main/java/com/ss/mqtt/broker/model/impl/DefaultMqttSession.java
> +        @NotNull PendingPacketHandler handler, int packetId
Wrong formatting

2019-11-29 18:19 UTC, crazyrokr approved these changes

2019-11-29 18:31 UTC, Wagos commented on src/main/java/com/ss/mqtt/broker/handler/packet/in/PublishAckInPacketHandler.java
> +public class PublishAckInPacketHandler extends PendingOutResponseInPacketHandler<PublishAckInPacket> {}
Could you use variable instead of empty classes?

2019-11-29 18:31 UTC, Wagos commented on src/main/java/com/ss/mqtt/broker/handler/publish/in/Qos2PublishInHandler.java
> +        }
Code duplication. Consider using Consumer interface

2019-11-29 18:31 UTC, Wagos commented on src/main/java/com/ss/mqtt/broker/handler/publish/in/Qos1PublishInHandler.java
> +        }
Code duplication. Consider using Consumer interface

2019-11-29 18:31 UTC, Wagos commented on src/main/java/com/ss/mqtt/broker/handler/packet/in/PublishReleaseInPacketHandler.java
> +        }
Code duplication. Consider using Consumer interface

2019-11-29 18:37 UTC, merged